server {
    listen 80;
    listen [::]:80;

    root /var/www/blog/public;
    index index.html;

    gzip on;
    gzip_types text/css text/plain application/json text/html application/javascript;

    location / {
        try_files $uri $uri/ =404;
    }
}
